id: P007911
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:44.343347
source_metadata:
  id: bdr:W8LS18472
  title: དམངས་སྲོལ་རིག་པ་སྤྱི་བཤད།
  author: ''
  volumes:
    acf788e213584c8b90411cc73a02d38b:
      image_group_id: I8LS18474
      title: Volume 1 of dmangs srol rig pa spyi bshad/
      volume_number: 1
      total_pages: 255
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
