id: P007911
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18472
  title: དམངས་སྲོལ་རིག་པ་སྤྱི་བཤད།
  author: ''
  volumes:
    cba712a1b3254747badb74920e1f3f6c:
      image_group_id: I8LS18474
      title: ''
      volume_number: 1
      total_pages: 255
ebook_metadata:
  title: དམངས་སྲོལ་རིག་པ་སྤྱི་བཤད།
  author: ''
  sku: P007911
  cover: cover.jpg
  layers:
  - pagination
